### ISSUE TITLE
cannot running Umbraco-RCE script

### ISSUE THREAD

**Issue by roigershon15** [noraj/Umbraco-RCE#2]
Hi,

i am using HachTheBox machine - Remote (10.10.10.180).
i have downloaded your script and tried to run it several times without success due to the following error message:

root@Kali:~/HTB_hacked/Remote# python2 exploit2.py -u x@x -p yyyyyyy -i 'http://10.10.10.180' -c powershell.exe -a 'ls c:'
  File "exploit2.py", line 1
    Skip to content
          ^
SyntaxError: invalid syntax
root@Kali:~/HTB_hacked/Remote# python exploit2.py -u admin@htb.local -p baconandcheese -i 'http://10.10.10.180' -c powershell.exe -a 'ls c:'
  File "exploit2.py", line 1
    Skip to content
          ^

===============
System Information:
Python version: Python 2.7.18rc1
python3 version: Python 3.8.2

root@Kali:~/HTB_hacked/Remote# lsb_release -a
No LSB modules are available.
Distributor ID: Kali
Description:    Kali GNU/Linux Rolling
Release:        2020.2
Codename:       kali-rolling

===============

can you please assist me with this issue? i am not sure why i cannot run this script on my Kali Linux machine.

**Comment by noraj** [comment]
1. Format your message https://help.github.com/en/github/writing-on-github/about-writing-and-formatting-on-github
2. You are running it with `python2`, and `python` on debian is a symlink to `python2` so you have write `python3` to use Python 3.
3. I'll remove your issue since you are leaking HTB credentials in it.
